config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:new, :index] do
    resources :comments, only: [:new]
  end

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :comments, only: [:create, :show]

  post '/posts/:id/upvote', to: 'posts#upvote', as: 'post_upvote'
  post '/posts/:id/downvote', to: 'posts#downvote', as: 'post_downvote'

  post '/comments/:id/upvote', to: 'comments#upvote', as: 'comment_upvote'
  post '/comments/:id/downvote', to: 'comments#downvote', as: 'comment_downvote'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  include Votable

  validates :content, :author, :post, presence: true

  belongs_to :author, class_name: :User
  belongs_to :post
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable
  end

  def upvote
    puts "Upvoted #{self}"
    self.votes << Vote.new(value: 1)
  end

  def downvote
    puts "Downvoted #{self}"
    self.votes << Vote.new(value: -1)
  end

end

app/models/post.rb
class Post < ApplicationRecord

  include Votable

  validates :title, :author, presence: true
  validates :subs, length: { minimum: 1, message: "Must be posted in at least 1 sub" }

  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs

  # belongs_to :sub
  belongs_to :author, class_name: :User

  has_many :comments

  # def top_level_comments
  #   self.comments.where(parent_comment_id: nil)
  # end

  def comments_by_parent_id
    grouped = Hash.new {|hash, key| hash[key] = Array.new }
    self.comments.each do |comment|
      grouped[comment.parent_comment_id] << comment
    end
    grouped
  end

end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true
  validates :post_id, uniqueness: { scope: :sub_id }

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :moderator, presence: true

  has_many :post_subs, inverse_of: :sub
  has_many :posts, through: :post_subs

  # has_many :posts
  belongs_to :moderator, class_name: :User
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password

  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_logged_in
    unless logged_in?
      flash[:errors] = ["You must log in"]
      redirect_to subs_url
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = this_comment
  end

  def upvote
    comment = this_comment
    comment.upvote
    redirect_to comment_url(comment)
  end

  def downvote
    comment = this_comment
    comment.downvote
    redirect_to comment_url(comment)
  end

  def this_comment
    Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_logged_in, only: [:new, :create]
  before_action :require_author, only: [:edit, :update]

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = this_post
  end

  def update
    @post = this_post
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = this_post
    @all_comments = @post.comments_by_parent_id
  end

  def destroy
    post = this_post
    post.destroy
    redirect_to sub_url(post.sub)
  end

  def upvote
    post = this_post
    post.upvote
    redirect_to post_url(post)
  end

  def downvote
    post = this_post
    post.downvote
    redirect_to post_url(post)
  end

  private

  def this_post
    Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_author
    author = Post.find(params[:id]).author
    redirect_to posts_url unless current_user = author
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login!(user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid Login"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_logged_in, only: [:new, :create]
  before_action :require_moderator, only: [:edit, :update]

  def require_moderator
    sub_moderator = Sub.find(params[:id]).moderator
    redirect_to subs_url unless current_user == moderator
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.nil?
      flash[:errors] = "Invalid Sub"
      render :edit
    elsif @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  # def destroy
  # end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{ form_authenticity_token}\">".html_safe
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<ul>
  <li><%= link_to comment.content, comment_url(comment) %></li>

  <% all_comments[comment.id].try(:each) do |c| %>
    <%= render 'comments/comment', comment: c, all_comments: all_comments %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">

  <label>Content
    <textarea name="comment[content]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" name="" value="Add Comment">
</form>

app/views/comments/show.html.erb
<h3>Content</h3>
<p> <%= @comment.content %> </p>
<br>

<%= button_to "Upvote", comment_upvote_url %>
<%= button_to "Downvote", comment_downvote_url %>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">

  <label>Reply to this comment
    <textarea name="comment[content]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" name="" value="Reply">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if logged_in? %>
      Signed in as <%= current_user.username %>
      <%= button_to "Sign Out", session_url, method: :delete %>
      <br>
    <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
    <% end %>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |err| %>
          <li> <%= err %> </li>
        <% end %>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% _action = params[:action] == "new" ? "POST" : "PATCH" %>
<% _url = params[:action] == "new" ? posts_url : post_url(post) %>
<% _button = params[:action] == "new" ? "Create Post" : "Update Post" %>

<%= _action %>
<%= _url %>

<form action="<%= _url %>" method="post">
  <input type="hidden" name="_method" value="<%= _action %>">
  <%= auth_token %>

  <label>Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>URL
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>Content
    <input type="textarea" name="post[content]" value="<%= post.content %>">
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |s| %>
    <label><%= s.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= s.id %>"
       <%= "checked" if post.sub_ids.include?(s.id) %> >
    </label>
  <% end %>

  <input type="submit" name="" value="<%= _button %>">

</form>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= link_to "Edit Post", edit_post_url(@post) %>

<h2><%= @post.title %></h2>
<h3> By: <%= @post.author.username %> </h3>

<%= button_to "Upvote", post_upvote_url %>
<%= button_to "Downvote", post_downvote_url %>

<h3>Posted In:</h3>
<% @post.subs.try(:each) do |sub| %>
  <ul>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  </ul>
<% end %>

Link: <%= link_to @post.title, @post.url %>

<p>
<%= @post.content %>
</p>

<h4>Comments</h4>

<%= link_to "Add a Comment", new_post_comment_url(@post) %>

<% @all_comments[nil].try(:each) do |comment| %>
  <%= render 'comments/comment', comment: comment, all_comments: @all_comments  %>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  <% @subs.try(:each) do |s| %>
  <li>
    <%= link_to "#{s.title}", sub_url(s) %>
  </li>
  <% end %>
</ul>

<%= link_to "Create New Sub", new_sub_url %>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <textarea name="sub[description]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" name="" value="Create New Sub">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h2>Moderator: <%= @sub.moderator.username %> </h2>
<br>

<% @sub.posts.each do |post| %>
  <%= link_to post.title, post_url(post)  %>
  <br>
<% end %>
<br>

<%= link_to "New Post", new_sub_post_url(@sub) %>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <br>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <br>

  <input type="submit" name="" value="Sign Up">
</form>